### ISSUE TITLE
Extracting marshaling code

### ISSUE THREAD

**Issue by Shadowfiend** [didiercrunch/paillier#3]
Hey there, we're working with this library for @keep-network. @pdyraga submitted #2 earlier this week, and we're interested in continuing to upstream further changes (if any); however, one of them is that we don't need the marshaling/unmarshaling code for BSON and JSON (we may need protobuf). We're thinking of refactoring the marshaling so that it can live in its own package and consumers can import the marshaling they need. Is that a change you'd be interested in pulling back into this repo?

**Comment by didiercrunch** [comment]
Totally, as a stand alone crypto package, the marshalling/unmarshalling
should be a separate issue.  Json might be ok to keep as it does not
require external dependancies but bson is a very odd dependency.  I would
totally accept any pull request in that direction.

Didier

**Comment by Shadowfiend** [comment]
Good to hear! Hope to offer up a PR soon :)

**Comment by Shadowfiend** [comment]
#4 closed this!
